name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - run: dotnet test ./TicTacToe.UnitTests/TicTacToe.UnitTests.csproj

  integration-tests:
    needs: unit-tests 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - run: dotnet test ./TicTacToe.IntegrationTests/TicTacToe.IntegrationTests.csproj

  build-app:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - run: dotnet build ./TicTacToe.API/TicTacToe.API.csproj --configuration Release